blog/urls.py
from django.urls import path
from .views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = "blog"
urlpatterns = [
    path('', BlogListView.as_view(), name="home"),
    path('create/', BlogCreateView.as_view(), name="create"),
    path('<int:pk>/', BlogDetailView.as_view(), name="detail"),
    path('<int:pk>/update/', BlogUpdateView.as_view(), name="update"),
    path('<int:pk>/delete/', BlogDeleteView.as_view(), name="delete"),
]

core/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name="home"),
    path('blog/', include('blog.urls', namespace='blog')),
]

blog/forms.py
from django import forms

from .models import Post
class PostCreateForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=('title','content')

core/views.py
from django.views.generic import View
from django.shortcuts import render
class HomeView(View):
    def get(self, request, *args, **kwargs):
        context={

        }
        return render (request, 'index.html', context)

core/templates/base.html
{% load static tailwind_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

     {% tailwind_css %}

    <title>Document</title>
</head>
<body>

    {% block content%} {% endblock content%}

</body>
</html>

core/templates/blog_create.html
<form method="POST">
    {% csrf_token %}
    title{{form.title}}
    <br>
    excerpt{{form.excerpt}}
    <br>
    content{{form.content}}
    <button type="submit">Submit</button>
</form>

core/templates/blog_delete.html
<form method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit">Delete</button>
</form>

core/templates/blog_detail.html
{{post.title}}
<br>
{{post.excerpt}}
<br>
{{post.content}}

core/templates/blog_list.html
{% extends 'base.html' %}

{% block content %}
	blog list
    <br>
    {%for post in posts%}
    <a href="{% url 'blog:detail' post.id %}">{{post.title}}</a>
    <a href="{% url 'blog:update' post.id %}">Update</a>
    <a href="{% url 'blog:delete' post.id %}">Delete</a>
    {%endfor%}
    <br>
<a class="inline-flex items-center px-2.5 py-1.5 border border-transparent text-xs font-medium rounded text-indigo-700 bg-indigo-100 hover:bg-indigo-200 focus:outline-none focus:ring-offset-2 focus:ring-indigo-500" href="{% url 'blog:create' %}">Create</a>
{% endblock content%}

core/templates/blog_update.html
<form method="POST">
    {% csrf_token %}
    title{{form.title}}
    <br>
    excerpt{{form.excerpt}}
    <br>
    content{{form.content}}
    <button type="submit">Update</button>
</form>

core/templates/index.html
{% extends 'base.html' %}
{% block content %}hola, visita mi <a class="text-blue-500" href="{% url 'blog:home' %}">blog aqui</a>{% endblock content%}